//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:55:24 ���� CST 
//


package com.dhb.mobile.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acqBIN",
    "date",
    "traceNum",
    "currency",
    "phnumber",
    "transAmt",
    "orderInfo",
    "merId",
    "orderNum"
})
@XmlRootElement(name = "Purchase")
public class InPurchase {
    @XmlElement(required = true)
    protected String acqBIN="";
    @XmlElement(required = true)
    protected String date="";
    @XmlElement(required = true)
    protected String traceNum="";
    @XmlElement(required = true)
    protected String currency="";

    @XmlElement(required = true)
    protected String phnumber;
    @XmlElement(required = true)
    protected String transAmt;
    @XmlElement(required = false)
    protected String orderInfo="";
    @XmlElement(required = true)
    protected String merId="";
    @XmlElement(required = true)
    protected String orderNum="";
	public String getAcqBIN() {
		return acqBIN;
	}
	public void setAcqBIN(String acqBIN) {
		this.acqBIN = acqBIN;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public String getTraceNum() {
		return traceNum;
	}
	public void setTraceNum(String traceNum) {
		this.traceNum = traceNum;
	}
	public String getCurrency() {
		return currency;
	}
	public void setCurrency(String currency) {
		this.currency = currency;
	}
	public String getPhnumber() {
		return phnumber;
	}
	public void setPhnumber(String phnumber) {
		this.phnumber = phnumber;
	}
	public String getTransAmt() {
		return transAmt;
	}
	public void setTransAmt(String transAmt) {
		this.transAmt = transAmt;
	}
	public String getOrderInfo() {
		return orderInfo;
	}
	public void setOrderInfo(String orderInfo) {
		this.orderInfo = orderInfo;
	}
	public String getMerId() {
		return merId;
	}
	public void setMerId(String merId) {
		this.merId = merId;
	}
	public String getOrderNum() {
		return orderNum;
	}
	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

}
