//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:55:24 ���� CST 
//


package com.dhb.mobile.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msg",
    "account",
    "purchase",
    "extInfo",
    "pubKeyIndex",
    "ticket"
})
@XmlRootElement(name = "Quanbody")
public class InQuanbody {

    @XmlElement(name = "Msg", required = true)
    protected InMsg msg;
    @XmlElement(name = "Account", required = true)
    protected InAccount account;
    @XmlElement(name = "Purchase", required = true)
    protected InPurchase purchase;
    
    @XmlElement(name = "extInfo", required = false)
    protected String extInfo;
    @XmlElement(name = "PubKeyIndex", required = true)
    protected String pubKeyIndex;
    @XmlElement(name = "Ticket", required = true)
    protected String ticket;
	public InMsg getMsg() {
		return msg;
	}
	public void setMsg(InMsg msg) {
		this.msg = msg;
	}
	public InAccount getAccount() {
		return account;
	}
	public void setAccount(InAccount account) {
		this.account = account;
	}
	public InPurchase getPurchase() {
		return purchase;
	}
	public void setPurchase(InPurchase purchase) {
		this.purchase = purchase;
	}
	public String getExtInfo() {
		return extInfo;
	}
	public void setExtInfo(String extInfo) {
		this.extInfo = extInfo;
	}
	public String getPubKeyIndex() {
		return pubKeyIndex;
	}
	public void setPubKeyIndex(String pubKeyIndex) {
		this.pubKeyIndex = pubKeyIndex;
	}
	public String getTicket() {
		return ticket;
	}
	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

    
}
