//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:55:24 ���� CST 
//


package com.dhb.mobile.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quanbody",
    "secureData"
})
@XmlRootElement(name = "Quan")
public class InQuan {

    @XmlElement(name = "Quanbody", required = true)
    protected InQuanbody quanbody;
    
    @XmlElement(name = "SecureData", required = true)
    protected String secureData;

	public InQuanbody getQuanbody() {
		return quanbody;
	}

	public void setQuanbody(InQuanbody quanbody) {
		this.quanbody = quanbody;
	}

	public String getSecureData() {
		return secureData;
	}

	public void setSecureData(String secureData) {
		this.secureData = secureData;
	}


}
