//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:55:24 ���� CST 
//


package com.dhb.mobile.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msg",
    "account",
    "purchase",
    "resp",
    "stpp",
    "extInfo",
    "pubKeyIndex",
    "ticket"
})
@XmlRootElement(name = "Quanbody")
public class OutQuanbody {

    @XmlElement(name = "Msg", required = true)
    protected OutMsg msg;
    @XmlElement(name = "Account", required = true)
    protected OutAccount account;
    @XmlElement(name = "Purchase", required = true)
    protected OutPurchase purchase;
    @XmlElement(name = "Resp", required = true)
    protected OutResp resp;
    @XmlElement(name = "STPP", required = true)
    protected OutSTPP stpp;
    
    @XmlElement(name = "extInfo", required = false)
    protected String extInfo;
    @XmlElement(name = "PubKeyIndex", required = false)
    protected String pubKeyIndex;
    @XmlElement(name = "Ticket", required = false)
    protected String ticket;
	public OutMsg getMsg() {
		return msg;
	}
	public void setMsg(OutMsg msg) {
		this.msg = msg;
	}
	public OutAccount getAccount() {
		return account;
	}
	public void setAccount(OutAccount account) {
		this.account = account;
	}
	public OutPurchase getPurchase() {
		return purchase;
	}
	public void setPurchase(OutPurchase purchase) {
		this.purchase = purchase;
	}
	public OutResp getResp() {
		return resp;
	}
	public void setResp(OutResp resp) {
		this.resp = resp;
	}
	public OutSTPP getStpp() {
		return stpp;
	}
	public void setStpp(OutSTPP stpp) {
		this.stpp = stpp;
	}
	public String getExtInfo() {
		return extInfo;
	}
	public void setExtInfo(String extInfo) {
		this.extInfo = extInfo;
	}
	public String getPubKeyIndex() {
		return pubKeyIndex;
	}
	public void setPubKeyIndex(String pubKeyIndex) {
		this.pubKeyIndex = pubKeyIndex;
	}
	public String getTicket() {
		return ticket;
	}
	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

    
}
