//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:55:24 ���� CST 
//


package com.dhb.cgb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}tranCode"/>
 *         &lt;element ref="{}cifMaster"/>
 *         &lt;element ref="{}entSeqNo"/>
 *         &lt;element ref="{}tranDate"/>
 *         &lt;element ref="{}tranTime"/>
 *         &lt;element ref="{}retCode"/>
 *         &lt;element ref="{}entUserId"/>
 *         &lt;element ref="{}password"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tranCode",
    "cifMaster",
    "entSeqNo",
    "tranDate",
    "tranTime",
    "retCode",
    "entUserId",
    "password"
})
@XmlRootElement(name = "commHead")
public class CommHead {
	@XmlElement(required = true)
    protected String tranCode;
    protected String cifMaster;
    protected String entSeqNo;
    protected String tranDate;
    protected String tranTime;
    protected String retCode;
    @XmlElement(required = true)
    protected String entUserId;
    @XmlElement(required = true)
    protected String password;
    
	public String getTranCode() {
		return tranCode;
	}
	public void setTranCode(String tranCode) {
		this.tranCode = tranCode;
	}
	public String getCifMaster() {
		return cifMaster;
	}
	public void setCifMaster(String cifMaster) {
		this.cifMaster = cifMaster;
	}
	public String getEntSeqNo() {
		return entSeqNo;
	}
	public void setEntSeqNo(String entSeqNo) {
		this.entSeqNo = entSeqNo;
	}
	public String getTranDate() {
		return tranDate;
	}
	public void setTranDate(String tranDate) {
		this.tranDate = tranDate;
	}
	public String getTranTime() {
		return tranTime;
	}
	public void setTranTime(String tranTime) {
		this.tranTime = tranTime;
	}
	public String getRetCode() {
		return retCode;
	}
	public void setRetCode(String retCode) {
		this.retCode = retCode;
	}
	public String getEntUserId() {
		return entUserId;
	}
	public void setEntUserId(String entUserId) {
		this.entUserId = entUserId;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		//String content ="<![CDATA["+password+"]]>";
		//String content = 
		this.password = password;
	}

   
}
