//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.20 at 12:31:40 ���� CST 
//


package com.dhb.cgb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerSalarySeq",
    "retMes"
})
@XmlRootElement(name = "record")
public class OutBatchRecord {

    protected String customerSalarySeq;
    protected String retMes;
	public String getCustomerSalarySeq() {
		return customerSalarySeq;
	}
	public void setCustomerSalarySeq(String customerSalarySeq) {
		this.customerSalarySeq = customerSalarySeq;
	}
	public String getRetMes() {
		return retMes;
	}
	public void setRetMes(String retMes) {
		this.retMes = retMes;
	}
   

   
}
