//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:55:24 ���� CST 
//


package com.dhb.cgb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerBatchNo",
    "customerSalarySeq"
})
@XmlRootElement(name = "Body")
public class OutBatchQueryBody {

  private String customerBatchNo;
  private String customerSalarySeq;
public String getCustomerBatchNo() {
	return customerBatchNo;
}
public void setCustomerBatchNo(String customerBatchNo) {
	this.customerBatchNo = customerBatchNo;
}
public String getCustomerSalarySeq() {
	return customerSalarySeq;
}
public void setCustomerSalarySeq(String customerSalarySeq) {
	this.customerSalarySeq = customerSalarySeq;
}
  
  
  
}
