//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:55:24 ���� CST 
//


package com.dhb.cgb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "traceNo",
    "handleFee",
    "bigCheckFlag"
})
@XmlRootElement(name = "Body")
public class OutBodyResp {

    protected String traceNo="";
    protected String handleFee="";
    protected String bigCheckFlag="";
	public String getTraceNo() {
		return traceNo;
	}
	public void setTraceNo(String traceNo) {
		this.traceNo = traceNo;
	}
	public String getHandleFee() {
		return handleFee;
	}
	public void setHandleFee(String handleFee) {
		this.handleFee = handleFee;
	}
	public String getBigCheckFlag() {
		return bigCheckFlag;
	}
	public void setBigCheckFlag(String bigCheckFlag) {
		this.bigCheckFlag = bigCheckFlag;
	}
    

}
