//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 05:55:24 ���� CST 
//


package com.dhb.cgb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

    "origEntseqno",
    "origEntdate"
})
@XmlRootElement(name = "Body")
public class QueryBody {

    protected String origEntseqno="";

    protected String origEntdate="";

	public String getOrigEntseqno() {
		return origEntseqno;
	}

	public void setOrigEntseqno(String origEntseqno) {
		this.origEntseqno = origEntseqno;
	}

	public String getOrigEntdate() {
		return origEntdate;
	}

	public void setOrigEntdate(String origEntdate) {
		this.origEntdate = origEntdate;
	}
   


}
