//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.20 at 12:31:40 ���� CST 
//


package com.dhb.cgb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}customerSalarySeq"/>
 *         &lt;element ref="{}transType"/>
 *         &lt;element ref="{}inaccname"/>
 *         &lt;element ref="{}inacc"/>
 *         &lt;element ref="{}inaccbank"/>
 *         &lt;element ref="{}inaccadd"/>
 *         &lt;element ref="{}bankCode"/>
 *         &lt;element ref="{}salary"/>
 *         &lt;element ref="{}remark"/>
 *         &lt;element ref="{}comment"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerSalarySeq",
    "transType",
    "inaccname",
    "inacc",
    "inaccbank",
    "inaccadd",
    "bankCode",
    "salary",
    "remark",
    "comment"
})
@XmlRootElement(name = "record")
public class Record {

    protected String customerSalarySeq;
    protected String transType;
    protected String inaccname;
    protected String inacc;
    protected String inaccbank;
    protected String inaccadd;
    protected String bankCode;
    protected Double salary;
    protected String remark;
    protected String comment;
	public String getCustomerSalarySeq() {
		return customerSalarySeq;
	}
	public void setCustomerSalarySeq(String customerSalarySeq) {
		this.customerSalarySeq = customerSalarySeq;
	}
	public String getTransType() {
		return transType;
	}
	public void setTransType(String transType) {
		this.transType = transType;
	}
	public String getInaccname() {
		return inaccname;
	}
	public void setInaccname(String inaccname) {
		this.inaccname = inaccname;
	}
	public String getInacc() {
		return inacc;
	}
	public void setInacc(String inacc) {
		this.inacc = inacc;
	}
	public String getInaccbank() {
		return inaccbank;
	}
	public void setInaccbank(String inaccbank) {
		this.inaccbank = inaccbank;
	}
	public String getInaccadd() {
		return inaccadd;
	}
	public void setInaccadd(String inaccadd) {
		this.inaccadd = inaccadd;
	}
	public String getBankCode() {
		return bankCode;
	}
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}
	public Double getSalary() {
		return salary;
	}
	public void setSalary(Double salary) {
		this.salary = salary;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}

   
}
