//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.20 at 12:31:40 ���� CST 
//


package com.dhb.cgb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}customerSalarySeq"/>
 *         &lt;element ref="{}transType"/>
 *         &lt;element ref="{}inaccname"/>
 *         &lt;element ref="{}inacc"/>
 *         &lt;element ref="{}inaccbank"/>
 *         &lt;element ref="{}inaccadd"/>
 *         &lt;element ref="{}bankCode"/>
 *         &lt;element ref="{}salary"/>
 *         &lt;element ref="{}remark"/>
 *         &lt;element ref="{}comment"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerSalarySeq",
    "transType",
    "employeeNo",
    "employeeName",
    "employeeAccount",
    "bankName",
    "bankCode",
    "salary",
    "remark",
    "comment"
})

@XmlRootElement(name = "record")
public class SendSalaryRecord {

    public String getEmployeeNo() {
		return employeeNo;
	}
	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}
	public String getEmployeeName() {
		return employeeName;
	}
	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
	public String getEmployeeAccount() {
		return employeeAccount;
	}
	public void setEmployeeAccount(String employeeAccount) {
		this.employeeAccount = employeeAccount;
	}
	public String getBankName() {
		return bankName;
	}
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
	protected String customerSalarySeq;
    protected String transType;
    protected String employeeNo;
    protected String employeeName;
    protected String employeeAccount;
    protected String bankName;
    protected String bankCode;
    protected Double salary;
    protected String remark;
    protected String comment;
	public String getCustomerSalarySeq() {
		return customerSalarySeq;
	}
	public void setCustomerSalarySeq(String customerSalarySeq) {
		this.customerSalarySeq = customerSalarySeq;
	}
	public String getTransType() {
		return transType;
	}
	public void setTransType(String transType) {
		this.transType = transType;
	}
	
	public String getBankCode() {
		return bankCode;
	}
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}
	public Double getSalary() {
		return salary;
	}
	public void setSalary(Double salary) {
		this.salary = salary;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}

   
}
